### ISSUE TITLE
Swagger 2.0 Spec

### ISSUE THREAD

**Issue by sgajavada** [swagger-api/swagger-node#180]
This module currently seems to be using swagger spec 1.2.  When will this module start supporting latest swagger spec 2.0?

Thanks.

**Comment by fela98** [comment]
+1

**Comment by DaniloOliveira28** [comment]
+1

**Comment by sobolk** [comment]
+1

**Comment by DinisCruz** [comment]
What is the difference between 1.2 and 2.0?

**Comment by fela98** [comment]
Here is a brief overview of the differences. 

https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide

These are the specs for detailed information: https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md

Fields are moved around and new useful features are added for example the 'allOf' schema field.

**Comment by webron** [comment]
The migration guide is *very* partial, unfortunately, but there are quite a few differences. Swagger 2.0 is a result of years of feedback from the community, and in fact, it was published after collaborative work with representatives from many companies.

It is simpler in structure and allows describing many use cases there were not available before.

**Comment by roman-io** [comment]
+1
Also looking at swaggerize-express by Paypal, which looks very nice.

**Comment by DinisCruz** [comment]
@roman-io , this one? https://github.com/krakenjs/swaggerize-express

**Comment by roman-io** [comment]
@DinisCruz Yes

**Comment by wonderlic-chrisk** [comment]
@fehguy, @webron, @jsdevel, Is there a rough timeline that you can share for the upgrade of swagger-node-express to support the 2.0 API or another version (swagger-n / apigee-127) we should start using instead? If you do intend to update this, ideally a date you are shooting for would be nice, but I think just a general "Q1 2015 / Q2 2015" would suffice for the moment.

**Comment by fehguy** [comment]
Hi @wonderlic-chrisk thanks for asking.  We're doing the planning for this after the swagger-js M2 release is out, which is planned for end of next week.  I agree we've been quiet on the upgrade plans but it's going to happen.  We're involving @whitlockjc as well as he's been working on some core tooling for 2.0 swagger on node

**Comment by fehguy** [comment]
Hi all, the current direction is very different from the current swagger-node-express module.  Taking advantage of [swagger-tools](https://github.com/apigee-127/swagger-tools), the swagger-spec can become a DSL rather than something generated by a library.  That keeps a single source of truth, and logic is simply a matter of routing operations to controllers.

Take a look here:

https://github.com/swagger-api/swagger-codegen/tree/develop_2.0/samples/server/petstore/nodejs

Structurally, it's very simple.  The swagger spec is under `api/swagger.json` and can be JSON or YAML syntax.  The controllers are under `controllers`.

And please send your feedback.  Overall I love this approach, and it's very much in the spirit of swagger, directionally (thanks to @whitlockjc for the awesome library)

**Comment by Freyert** [comment]
@fehguy I like the direction you all are taking this. I think it's incredibly useful to use the spec to generate the project scaffold. Personally, I'd like to see the project walk away from being middleware and focus more on being a plug and play generator; preferably Yeoman friendly. I think we'll start seeing more and more users walk away from Express in favor of Koa or some future modern framework. Therefore, I think it would be best if the project focused on being lean, pluggable, and solely focused on scaffolding NodeJS projects that have Swagger docs as per the Express team's philosophy.

How I imagine this working is you write up your Swagger doc in the directory you want to build your scaffolding in, and basically run it as if you were running a Yeoman generator. You'd be prompted several times to pick sub-generators for things like your models (Mongoose or ?), controllers (Express, Koa, or ?), and maybe even tests.

And if you needed to add more models or routes the generators could walk you through building those and add them to the swagger spec. Or perhaps if you modify the swagger doc the generator will know what was changed and act accordingly on the next command.

These are just some thoughts.

**Comment by whitlockjc** [comment]
@Freyert Agreed.  I think the low-level APIs/middleware will continue to be available as their own thing, although soon we'll be repackaging things so that getting what you want is easier without having to eat the whole elephant, but I do agree with a Yeoman-based, or equivalent, approach for creating Swagger+Node.js projects, validating them, etc.  We'll probably start with an opinionated _baseline_ with Express as the server and Waterline as the ORM _(if we go the route of doing ORM stuff)_ and then break that out into sub-generators.  This is all still up in the air as I've not put a lot of thought into swagger-tools or the Swagger+Node.js story much due to the pending M2 release of swagger-js/swagger-ui/swagger-core.

Expect more details soon.

**Comment by traxair** [comment]
+1

**Comment by fehguy** [comment]
This is handled in #209
