### ISSUE TITLE
Generating Swagger Documentation

### ISSUE THREAD

**Issue by jabr9983** [swagger-api/swagger-node#217]
Hello I am new to Swagger, is there a way to auto generate the yaml file in order to get the swagger documentation, I was referred to this page in order to accomplish this. After reading the documentation I had no success. I just don't really know anything about creating the yaml file so if I need to learn it I will, just wanted to see if there was an easier way first.

**Comment by prabhatjha** [comment]
What do you mean by autogenerate yaml file? I think you mean I already have a node.js API project and I want to generate Swagger API for that.

 This project is about design first API development workflow where you design your API in Swagger using bundled Swagger editor, implement your logic in controllers so that your implementation and documentations are always in synch. See more details at https://github.com/swagger-api/swagger-node/blob/master/docs/introduction.md

**Comment by jabr9983** [comment]
Yea that is what I mean, and I followed that but I couldn't seem to get it to create documentation from there, especially being that I am new to the API's in general any tips would be great.
