### ISSUE TITLE
Using Passport in a controller

### ISSUE THREAD

**Issue by skyserpent** [swagger-api/swagger-node#220]
Hello,

I'm trying to use Passport's 'authenticate' function inside of a controller function. However, I'm getting a hang up and it doesn't seem like Passport can recognize the request. What's the best way to go about this? I'm using a local strategy by the way.

**Comment by cirellamhcs** [comment]
Hi,

Possibly the same issue here:
I would like to use passport in my express app, normally you would do something like:

`app.get('/test', passport.authenticate('bearer', {session: false}), function(req,res) ...`

But since you define the routes in the yaml file, i am not sure how to build this. Is there a possibility to define this in the yaml file or can i do it differently?

Thanks in advance!

**Comment by theganyo** [comment]
You should be able to use this function in your controller by simply calling it with the parameters passed to you like so:

    passport.authenticate('bearer', {session: false})(req, res, next);
