### ISSUE TITLE
Renaming Swagger configuration file?

### ISSUE THREAD

**Issue by bixibu** [swagger-api/swagger-node#284]
Hi

Is there a way to rename the ``config/default.yaml`` file ?
I have a few config files in here related to all sort of things (database, logs, etc), and the "default.yaml"  related to swagger is a bit unclear to me.

By the way, if I don't use swagger project start (I integrated swagger-node in an existing project), do this config file is of any utility for me ? What is its goal ?

Thanks

**Comment by theganyo** [comment]
No, you can't currently rename default.yaml... but you don't need to use or have default.yaml for anything if you have your own configuration files and pass in any swagger-node specific configuration. The code generated for app.js looks like this:

```
var config = {
  appRoot: __dirname // required config
};

SwaggerConnect.create(config, function(err, swaggerConnect) {
```

So, at this point you may pass in whatever config you want for swagger-node instead of relying on default.yaml. The config that you pass in would be assigned to what would have been in default.yaml under the "swagger" key.

**Comment by bixibu** [comment]
Thanks a lot ! That's perfect
