### ISSUE TITLE
How to handle endpoint versions

### ISSUE THREAD

**Issue by justechn** [swagger-api/swagger-node#398]
I am just getting started with this and I am unsure of how to handle endpoint versions. I am converting our current endpoint to use this, and have need of a v1 and v2 endpoints.

I can add a v1 or v2 in name, but that seems redundant. Is there a better way to do this?

**Comment by justechn** [comment]
So, is this project dead? There are a lot of issues that are not getting any response. This concerns me because I don't want to take the time to implement a library that is not going to be supported.

**Comment by fehguy** [comment]
Routing based on versions has no single answer--you can use URL based routing, header based routing, or even parameter based routing.  I'd suggest picking a strategy based on your use case and traffic, and then implementation is pretty easy.  That design is outside of this projects' scope though, but you can use this with any of the three approaches I mentioned.  Usually there's a reverse proxy in front, like HAProxy or even NGINX.

**Comment by justechn** [comment]
Thanks for this, I will be using URL based routing, but that brings up another question. After a few versions the swagger file is going to get really cluttered. Can the swagger.yml files be split up for better organization?

**Comment by fehguy** [comment]
@justechn yes, there are limitations but you can certainly split up the swagger files.  But a couple thoughts first.

Most of the time, the APIs are different enough that people run multiple application servers behind a proxy server.  So you would redirect all traffic that starts with `/v2` to your v2 application server, etc.  Thus you don't need to worry about the swagger file getting cluttered--you literally have multiple files because you have multiple servers.

But you can certainly split using the `$ref` syntax.  It's not allowable in every place, so you would be using the `Path Item Object` most likely.

So you could say `/v2/foo` is defined in an external file with `$ref`.  Likewise you could add `/v3/foo` into a different file.  Let me know if that doesn't make sense.
