### ISSUE TITLE
npm ERR! cb() never called!

### ISSUE THREAD

**Issue by Ziv-Barber** [swagger-api/swagger-node#474]
Howto:

npm install -g swagger

Will result:

npm ERR! cb() never called!

More information:

npm -v
3.8.3

node -v
v5.9.1

node install for anything else working fine.

**Comment by justinhhorner** [comment]
Hi @Ziv-Barber, 

I'm able to successfully `npm install -g swagger` using: 

Node 6.9.1 / NPM 3.10.8
Node 5.8.0 / NPM 4.0.5

If you haven't already, you may want to try clearing the NPM cache and attempt the install again. From what I've read, that could resolve the issue in some cases.

It's possible that this an issue in previous versions of NPM that's been resolved since the release of 4.x. Please let us know if you find a solution.

**Comment by Ziv-Barber** [comment]
It do working for me in another computer with:

npm 3.7.2
node 6.4.0

Back to the computer with the problem:

I tried to clean the cache.
I tried to install a new version of npm.
No luck.

**Comment by fehguy** [comment]
seems like something in your environment.  If you have other issues, please reopen.
